---
title: "Walinchus Astronomy"
author: "David H. Montgomery"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(ggforce)
library(ggrepel)
```

```{r loaddata}
space_data <- read_csv("https://raw.githubusercontent.com/dhmontgomery/walinchus-astronomy/master/space_data.csv") %>%
	janitor::clean_names()
```

```{r distance_plot, message = FALSE}
space_data %>%
	mutate(across(-object, as.numeric)) %>%
	filter(!is.na(distance_from_sun_million_km)) %>%
	mutate(object = str_remove_all(object, "\\(an asteroid\\)")) %>%
	ggplot(aes(x = fct_reorder(object, distance_from_sun_million_km), y = distance_from_sun_million_km)) +
	geom_col() +
	scale_y_continuous(labels = comma) +
	labs(title = "Distance from the Sun",
		 y = "Millions of kilometers",
		 x = "Celestial body",
		 caption = "Graph by David H. Montgomery")
ggsave("distance_from_the_sun.png", width = 8, height = 6)
```

```{r distance_plot_pretty, message = FALSE}
space_data %>%
	mutate(across(-object, as.numeric)) %>%
	filter(!is.na(distance_from_sun_million_km)) %>%
	mutate(object = str_remove_all(object, "\\(an asteroid\\)")) %>%
	ggplot(aes(x = fct_reorder(object, distance_from_sun_million_km, .desc = TRUE), y = distance_from_sun_million_km)) +
	geom_col() +
	geom_text(aes(label = comma(distance_from_sun_million_km, accuracy = .1), 
				  hjust = case_when(distance_from_sun_million_km < 500 ~ -.1, TRUE ~ 1.1),
				  color = case_when(distance_from_sun_million_km < 500 ~ "black", TRUE ~ "white"))) +
	scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.05))) +
	scale_color_identity() +
	coord_flip() +
	labs(title = "Distance from the Sun (millions of kilometers)",
		 y = "Millions of kilometers",
		 x = "Celestial body",
		 caption = "Graph by David H. Montgomery") +
	theme_minimal() +
	theme(axis.title = element_blank(),
		  axis.text.x = element_blank(),
		  panel.grid.major.y = element_blank(),
		  panel.grid.minor.y = element_blank())
ggsave("distance_from_the_sun_pretty.png", width = 8, height = 6)
```


```{r radius, message = FALSE, warning = FALSE}
space_data %>%
	mutate(across(-object, as.numeric)) %>%
	filter(!is.na(distance_from_sun_million_km)) %>%
	mutate(object = str_remove_all(object, "\\(an asteroid\\)")) %>%
	ggplot() +
	geom_circle(aes(x0 = 0, y0 = 0, r = distance_from_sun_million_km), size = .2, color = "grey90") +
	geom_point(aes(x = 0, y = distance_from_sun_million_km, size = diameter_km)) +
	geom_label(data = . %>% filter(distance_from_sun_million_km > 500), aes(x = 0, y = distance_from_sun_million_km, label = object), hjust = 0, nudge_x = 350, color = NA, alpha = .5) +
	geom_text(data = . %>% filter(distance_from_sun_million_km > 500), aes(x = 0, y = distance_from_sun_million_km, label = object), hjust = 0, nudge_x = 350) +
	scale_size_continuous(labels = comma, breaks = c(1000, 10000, 100000)) +
	coord_fixed() +
	theme_void() +
	labs(title = "Distance from the Sun",
		 caption = "Graph by David H. Montgomery",
		 size = "Diameter (km)")
ggsave("distance_from_the_sun_circles.png", width = 8, height = 6)
```


```{r}
space_data %>%
	mutate(across(-object, as.numeric)) %>%
	filter(!is.na(distance_from_sun_million_km)) %>%
	mutate(object = str_remove_all(object, "\\(an asteroid\\)")) %>%
	ggplot(aes(x = temperature_min_c, y = temperature_max_c)) +
	geom_point() +
	geom_text_repel(aes(label = object)) +
	theme_minimal() +
	coord_fixed(clip = "off") +
	labs(title = "Minimum and maximum temperatures",
		 caption = "Graph by David H. Montgomery",
		 x = "Minimum temperature (Celsius)",
		 y = "Maximum temperature (Celsius)")
ggsave("temperature.png", width = 7, height = 7)
```


